spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# AUTH
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# PRODUCT
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**

# STOCK
spring.cloud.gateway.server.webflux.routes[2].id=stock-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://stock-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/stocks/**

# CART
spring.cloud.gateway.server.webflux.routes[3].id=shopping-cart-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://shopping-cart-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/cart/**

# ORDER
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/orders/**

# PAYMENT
spring.cloud.gateway.server.webflux.routes[5].id=payment-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/payments/**

# LOG
spring.cloud.gateway.server.webflux.routes[6].id=log-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://log-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/logs/**

management.endpoints.web.exposure.include=health,info,gateway

# SWAGGER ROUTES
spring.cloud.gateway.server.webflux.routes[7].id=user-service-docs
spring.cloud.gateway.server.webflux.routes[7].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/user-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[8].id=product-service-docs
spring.cloud.gateway.server.webflux.routes[8].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/product-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[8].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[9].id=stock-service-docs
spring.cloud.gateway.server.webflux.routes[9].uri=lb://stock-service
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/stock-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[9].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[10].id=cart-service-docs
spring.cloud.gateway.server.webflux.routes[10].uri=lb://shopping-cart-service
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/cart-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[10].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[11].id=order-service-docs
spring.cloud.gateway.server.webflux.routes[11].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/order-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[11].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[12].id=payment-service-docs
spring.cloud.gateway.server.webflux.routes[12].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/payment-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[12].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[13].id=log-service-docs
spring.cloud.gateway.server.webflux.routes[13].uri=lb://log-service
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/log-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[13].filters[0]=StripPrefix=1

# SWAGGER UI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Product Service
springdoc.swagger-ui.urls[1].url=/product-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Stock Service
springdoc.swagger-ui.urls[2].url=/stock-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Cart Service
springdoc.swagger-ui.urls[3].url=/cart-service/v3/api-docs
springdoc.swagger-ui.urls[4].name=Order Service
springdoc.swagger-ui.urls[4].url=/order-service/v3/api-docs
springdoc.swagger-ui.urls[5].name=Payment Service
springdoc.swagger-ui.urls[5].url=/payment-service/v3/api-docs
springdoc.swagger-ui.urls[6].name=Log Service
springdoc.swagger-ui.urls[6].url=/log-service/v3/api-docs