spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Mail ayarları (Gmail örneği)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=m.alperenk@gmail.com
spring.mail.password=pfrk krbu pdxb lcra
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

# Her servise maximum bağlantı limiti ekle
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1