spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Iyzico Sandbox bilgileri
iyzico.api-key=sandbox-Z1NOGglOMHX6OQkVDEkyxnPk0MDv0XnK
iyzico.secret-key=sandbox-gVsOhbdQoiFa0IHXCyrYMuGwgherRXug
iyzico.base-url=https://sandbox-api.iyzipay.com

# Her servise maximum bağlantı limiti ekle
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1