# Veritabanı Ayarları (Localhost)
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ Ayarları (Localhost)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Hikari Bağlantı Havuzu (Lokal testlerde çok kısıtlamaya gerek olmayabilir ama kalsın dersen)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1