spring.datasource.url=jdbc:postgresql://user-db:5432/stock_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

# Her servise maximum bağlantı limiti ekle
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1